apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot
        source:
          git:
            url: https://github.com/stevef1uk/jdg-bootkafka-example.git
            revision: master
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: docker.io/stevef1uk/jdg-bootkafka-example:latest
      revisionTemplate:
        spec:
          container:
            image: docker.io/stevef1uk/jdg-bootkafka-example:latest 
            imagePullPolicy: Always
            env:
            - name: SIMPLE_MSG
              value: "Hello sample Java Spring Boot sample Kafka app!"
